### ISSUE TITLE
Include option to provide more simple Yes/No rating instead of 1-5

### ISSUE THREAD

**Issue by madmatt** [vulcandigital/silverstripe-pagefeedback#4]
Hey @zanderwar,

Keen to hear what you think about adding an option to this module that lets you specify two options for feedback. Either:

- The existing option to rate between 1 and 5
- A new option to provide either a +1 or -1 (e.g. "Yes" or "No")

The rest of this module would be great for us, but our current project is more likely to want a simpler interface than selecting a rating.

This could be based on YML config, and would only count ratings for a page based on the current config value (so if you swapped from one system to another, the old feedback entries would be counted in the summary).

Keen to see what you think before we start either extending this module or building a new one that's really similar.

We'd also like to add a `$has_one` linking a feedback entry to a Member for audit purposes - this could be optional, but could be made required via YML config.

Cheers,
Matt

**Comment by zanderwar** [comment]
I've been steering clear of 3.x series ever since 4.x has dropped. I do like your idea though, the `has_one` could be done via a `DataExtension`

It'd be great if you're keen to submit a PR? I won't be able to touch this for awhile

**Comment by zanderwar** [comment]
As per your suggest I have added a "thumbs" mode for the SS4 version and has been merged in (#5) however it'll still need to be ported back down to ss3, will get that done asap

**Comment by madmatt** [comment]
Hey that's awesome, thanks! We'll actually be using SS4 so no need to downgrade it to SS3 on our account :)

**Comment by zanderwar** [comment]
Awesome! Just make sure you use the `^2.0.x` branch when installing via composer, I have not actually tagged a release yet as I still have to fix up the CMS to show the two different modes correctly. (not production ready until release in other words)

I'll leave this ticket open until I port it to ss3

**Comment by zanderwar** [comment]
Closing this as I have no intention of porting to ss3 anymore :octocat:
